### ISSUE TITLE
routinator 0.15.2 on NetBSD needs a newer 'nix' crate

### ISSUE THREAD

**Issue by he32** [NLnetLabs/routinator#1104]
Routinator 0.15.2 failed to build out of the box on NetBSD with

```
error[E0425]: cannot find value `IFF_NOTRAILERS` in crate `libc`
  --> /usr/pkgsrc/net/routinator/work/vendor/nix-0.30.1/src/net/if_.rs:71:9
   |
71 |         IFF_NOTRAILERS as IflagsType;
   |         ^^^^^^^^^^^^^^ not found in `libc`
   |
  ::: /usr/pkgsrc/net/routinator/work/vendor/nix-0.30.1/src/macros.rs:72:27
   |
72 |                     const $Flag = libc::$Flag $(as $cast)*;
   |                           ----- due to this macro variable

For more information about this error, try `rustc --explain E0425`.
error: could not compile `nix` (lib) due to 1 previous error
*** Error code 101
```

`IFF_NOTRAILERS` was removed from NetBSD in 2019, and is not
defined by the `libc` crate referenced from routinator.  However, the
`nix` crate tries to use it, still.  It appears that newer `nix` versions no
longer try to define this on NetBSD, and routinator could therefore
consider updating its reference to the `nix` crate.

**Comment by partim** [comment]
That’s annoying. It looks like after updating the dependency to 0.31.3 Routinator will still happily build. Would you be okay working with a patch for now? We’re going to release 0.15.3 soon which will have all sorts of dependency updates.

**Comment by he32** [comment]
> That's annoying. It looks like after updating the dependency to
> 0.31.3 Routinator will still happily build. Would you be okay
> working with a patch for now?

I'm ahead of you. :)  Ref.

https://github.com/NetBSD/pkgsrc/blob/trunk/net/routinator/patches/patch-.._vendor_nix-0.30.1_src_net_if__.rs

and I've been running the result since yesterday.

> We're going to release 0.15.3 soon which will have all sorts of
> dependency updates.

OK, that's fine, so since the problem is worked around, there's
no need for anything more than bumping the 'nix' dependency for
the next release.
