### ISSUE TITLE
Issue building on FreeBSD

### ISSUE THREAD

**Issue by stucchimax** [NLnetLabs/routinator#1]
Hi,

I just tried building the project on FreeBSD after installing rust from packages.

This is the output I get:

```
Compiling ber v0.1.0 (https://github.com/NLnetLabs/ber-rs.git#18a0b990)
Compiling rpki v0.1.0 (https://github.com/NLnetLabs/rpki-rs.git#8cd80010)
error[E0658]: use of unstable library feature 'slice_rsplit' (see issue #41020)
  --> /root/.cargo/git/checkouts/rpki-rs-a43ad3b5562cba05/8cd8001/src/rsync.rs:85:30
   |
85 |         let tail = self.path.rsplit(|ch| *ch == b'/').next().unwrap().len();
   |                              ^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `rpki`.

To learn more, run the command again with --verbose.
#
```

I'm running everything as root.  It's a test vm I created just for this, so nothing else is running and is installed there.

**Comment by partim** [comment]
Which version of Rust do you have? You can check with `rustc --version`.

Turns out you need 1.27 as slice's `rfind` method was stabilized only then.

Looking at FreeBSD's port list, it should have rust-1.27.1, so maybe just update?

Sorry about this. I'll add some more specific information about the required version to the README.

**Comment by Jakker** [comment]
Martin Hoffmann writes:

 > Which version of Rust do you have? You can check with `rustc --version`.
 >
 > Turns out you need 1.27 as slice's `rfind` method was stabilized only then.
 >
 > Looking at FreeBSD's port list, it should have rust-1.27.1, so maybe just update?
 >

Yes, it builds with 1.27.1 from the ports, no problem.

I'm trying to turn it into a port to make live easier for FreeBSD
users, It runs into other problems doing that. That has to wait to
after the weekend.

	jap

**Comment by stucchimax** [comment]
Strange, I installed rust from ports and I got 1.26.2.

I'm now proceeding to install rust from ports and will let you know.

Thanks

**Comment by Jakker** [comment]
Massimiliano Stucchi writes:

 > Strange, I installed rust from ports and I got 1.26.2.
 >

[jaap@bela ~]$ rustc --version
rustc 1.27.1

 > I'm now proceeding to install rust from ports and will let you know.
 >

Make sure you updated the ports as well. 1.27.1 in ports is pretty recent as shown by:

	(cd /usr/ports/lang/rust; svn log | sed 60q; )

 > Thanks

Succes!

jaap

**Comment by stucchimax** [comment]
On 28/07/2018 10:39, Jaap Akkerhuis wrote:
> Massimiliano Stucchi writes:
> 
>> Strange, I installed rust from ports and I got 1.26.2.

I actually meant to say I installed from packages.  I just noticed the
mistake here.

Packages have 1.26.2.

> [jaap@bela ~]$ rustc --version
> rustc 1.27.1
> 
>> I'm now proceeding to install rust from ports and will let you know.
>>
> 
> Make sure you updated the ports as well. 1.27.1 in ports is pretty
> recent as shown by:
> 
> (cd /usr/ports/lang/rust; svn log | sed 60q; )

Yes.  Then I ran into another issue:  I figured you can't build rust
with 1GB of RAM.  I had to up to 4GB and then it cleanly compiled from
ports.

I was then able to run routinator.

Ciao!

-- 

Massimiliano Stucchi
MS16801-RIPE

**Comment by stucchimax** [comment]
In the end, apart from some FreeBSD-specific issues, everything is fine.
